version: '3.6'

services:
  hapi-fhir-mysql:
    image: mysql:latest
    container_name: hapi-fhir-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - 3307:3306
    volumes:
      - hapi-fhir-mysql:/var/lib/mysql

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27018:27017

  hapi-fhir-jpaserver:
    image: greenemcg/hapi-fhir-jpaserver
    container_name: hapi-fhir-jpaserver
    environment:
      HAPI_FHIR_URL_PUBLIC: ${HAPI_FHIR_URL_PUBLIC}
      HAPI_DB_URL: ${HAPI_DB_URL}
      HAPI_DB_USER: ${HAPI_DB_USER}
      HAPI_DB_PASS: ${HAPI_DB_PASS}
    ports:
      - 6060:6060

  cql-elm-translation:
    image: cql-elm-translation
    container_name: cql-elm-translation
    build:
      context: cql-elm-translation
      dockerfile: Dockerfile
    environment:
      FHIR_SERVICES_URL: ${FHIR_SERVICES_URL}
    ports:
      - 7070:7070

  mapping-services:
    image: mapping-services
    container_name: mapping-services
    build:
      context: mapping-services
      dockerfile: Dockerfile
    environment:
      GOOGLE_MAT_ATTRIBUTES_URL: ${GOOGLE_MAT_ATTRIBUTES_URL}
      GOOGLE_QDM_QI_CORE_MAPPING_URL: ${GOOGLE_QDM_QI_CORE_MAPPING_URL}
      GOOGLE_DATA_TYPES_URL: ${GOOGLE_DATA_TYPES_URL}
      GOOGLE_REQUIRED_MEASURE_FIELDS_URL: ${GOOGLE_REQUIRED_MEASURE_FIELDS_URL}
      GOOGLE_RESOURCE_DEFINITION_URL: ${GOOGLE_RESOURCE_DEFINITION_URL}
    ports:
      - 9090:9090

  mat-fhir-services:
    image: mat-fhir-services
    container_name: mat-fhir-services
    build:
      context: mat-fhir-services
      dockerfile: Dockerfile
    environment:
      VSAC_VASE_URL: ${VSAC_VASE_URL}
      VSAC_SERVICE_URL: ${VSAC_SERVICE_URL}
      MAT_DB_URL: ${MAT_DB_URL}
      MAT_DB_PASS: ${MAT_DB_PASS}
      MAT_DB_USER: ${MAT_DB_USER}
      MONGO_DB_URL: ${MONGO_DB_URL}
      HAPI_FHIR_URL: ${HAPI_FHIR_URL}
      QDM_QICORE_URL: ${QDM_QICORE_URL}
      CQL_CONVERSION_URL: ${CQL_CONVERSION_URL}
      FHIR_SERVICES_URL: ${FHIR_SERVICES_URL}
      MAT_LOG_LEVEL: ${MAT_LOG_LEVEL}
      CODESYSTEM_SHEET_URL: ${CODESYSTEM_SHEET_URL}
      HAPI_FHIR_URL_PUBLIC: ${HAPI_FHIR_URL_PUBLIC}
    ports:
      - 9080:9080

volumes:
  hapi-fhir-mysql: