version: '3.6'

services:
  hapi-fhir-mysql:
    image: mysql:latest
    container_name: hapi-fhir-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - 3307:3306
    volumes:
      - hapi-fhir-mysql:/var/lib/mysql

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27018:27017

  hapi-fhir-jpaserver:
    image: greenemcg/hapi-fhir-jpaserver
    container_name: hapi-fhir-jpaserver
    ports:
      - 6060:6060

  cql-elm-translation:
    image: cql-elm-translation
    container_name: cql-elm-translation
    build:
      context: cql-elm-translation
      dockerfile: Dockerfile
    environment:
      FHIR_SERVICES_URL: ${FHIR_SERVICES_URL}
    ports:
      - 7070:7070

  qdm-qicore-mapping-services:
    image: qdm-qicore-mapping-services
    container_name: qdm-qicore-mapping-services
    build:
      context: qdm-qicore-mapping-services
      dockerfile: Dockerfile
    environment:
      QDM_SPREADSHEET: ${QDM_SPREADSHEET}
    ports:
      - 9090:9090

  mat-fhir-services:
    image: mat-fhir-services
    container_name: mat-fhir-services
    build:
      context: mat-fhir-services
      dockerfile: Dockerfile
    environment:
      VSAC_VASE_URL: ${VSAC_VASE_URL}
      VSAC_SERVICE_URL: ${VSAC_SERVICE_URL}
      MAT_DB_URL: ${MAT_DB_URL}
      MAT_DB_PASS: ${MAT_DB_PASS}
      MAT_DB_USER: ${MAT_DB_USER}
      MONGO_DB_URL: ${MONGO_DB_URL}
      HAPI_FHIR_URL: ${HAPI_FHIR_URL}
      QDM_QICORE_URL: ${QDM_QICORE_URL}
      CQL_CONVERSION_URL: ${CQL_CONVERSION_URL}
      FHIR_SERVICES_URL: ${FHIR_SERVICES_URL}
    ports:
      - 9080:9080

volumes:
  hapi-fhir-mysql: