spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${MAT_DB_URL:jdbc:mysql://localhost:3306/MAT?serverTimezone=UTC&max_allowed_packet=16777216}
    username: ${MAT_DB_USER:mat}
    password: ${MAT_DB_PASS:mat}
  jpa:
    hibernate.ddl-auto: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    show-sql: false
  data:
    mongodb:
      database: mat_conversion_results
      uri: ${MONGO_DB_URL}

logging:
  level:
    root: INFO
    gov.cms.mat: DEBUG
    org.hl7.fhir.r4.hapi.ctx: WARN
    org.exolab: WARN
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %mdc %-5level %logger{36}.%M - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %mdc %logger{36}.%M - %msg%n"
  file:
    name: mat-fhir-services.log

fhir:
  r4:
    baseurl: ${HAPI_FHIR_URL}

cql:
  conversion:
    baseurl: ${CQL_CONVERSION_URL}

self:
  health:
    baseurl: ${FHIR_SERVICES_URL}/mat-fhir-serives/

mapping:
  services:
    baseUrl: ${QDM_QICORE_MAPPING_SERVICES_URL}
