server:
  port: 9080

spring:
  profiles:
    active: local
  jpa:
    open-in-view: false

vsac-client:
  server: ${VSAC_VASE_URL}/vsac/ws/Ticket
  service: ${VSAC_SERVICE_URL}
  retrieve-multi-oids-service: ${VSAC_VASE_URL}/vsac/svs/RetrieveMultipleValueSets?
  profile-service: ${VSAC_VASE_URL}/vsac/profiles
  version-service: ${VSAC_VASE_URL}/vsac/oid/
  vsac-server-drc-url: ${VSAC_VASE_URL}/vsac
  use-cache: on
  cache-directory: /opt/vsac/cache

mat.codesystem.valueset.simultaneous.validations: 5
mat.qdm.default.expansion.id: Most Recent Code System Versions in VSAC

conversion-lib-lookup-4-1:
  map:
    FHIRHelpers: 4.0.001
    AdultOutpatientEncounters: 2.0.000
    AdvancedIllnessandFrailtyExclusion: 5.0.000
    Hospice: 2.0.000
    MATGlobalCommonFunctions: 5.0.000
    SupplementalDataElements: 2.0.000
    TJCOverall: 5.0.000
    VTEICU: 4.0.000


measures:
  allowed:
    versions: v5.5,v5.6,v5.7,v5.8,v5.9,v6.0

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Mat Fhir Services
