server:
  port: 9080


spring:
  profiles:
    active: local
  jpa:
    open-in-view: false

vsac-client:
  server: https://vsac.nlm.nih.gov/vsac/ws/Ticket
  service: http://umlsks.nlm.nih.gov
  retrieve-multi-oids-service: https://vsac.nlm.nih.gov/vsac/svs/RetrieveMultipleValueSets?
  profile-service: https://vsac.nlm.nih.gov/vsac/profiles
  version-service: https://vsac.nlm.nih.gov/vsac/oid/
  vsac-server-drc-url: https://vsac.nlm.nih.gov/vsac
  use-cache: on
  cache-directory: /opt/vsac/cache

measures:
  allowed:
    versions: v5.5,v5.6,v5.7,v5.8,v5.9,v6.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

