spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/${MAT_DB}?serverTimezone=UTC&max_allowed_packet=16777216
    username: ${MAT_DB_USER}
    password: ${MAT_DB_PASS}
  jpa:
    hibernate.ddl-auto: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl    
    generate-ddl: false
    show-sql: false
  data:
    mongodb:
      database: mat_conversion_results
      uri: mongodb://mongo

logging:
  level:
    root: INFO
    gov.cms.mat: DEBUG
    org.hl7.fhir.r4.hapi.ctx: WARN
    org.exolab: WARN
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  file:
    name: mat-fhir-services.log

fhir:
  r4:
    baseurl: http://hapi-fhir-jpaserver:6060/hapi-fhir-jpaserver/fhir/

qdmqicore:
  conversion:
    baseurl: http://qdm-qicore-mapping-services:9090

cql:
  conversion:
    baseurl: http://cql-elm-translation:7070

self:
  health:
    baseurl: http://docker.for.mac.localhost:${server.port}

