spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${MAT_DB_URL}
    username: ${MAT_DB_USER}
    password: ${MAT_DB_PASS}
  jpa:
    hibernate.ddl-auto: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    show-sql: false

logging:
  level:
    root: INFO
    gov.cms.mat: INFO
    org.hl7.fhir.r4.hapi.ctx: INFO
    org.exolab: WARN
    org.springframework.data.mongodb.core.MongoTemplate: WARN
    org.hl7.fhir.r4.hapi.validation: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %mdc %-5level %logger{36}.%M - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %mdc %logger{36}.%M - %msg%n"
  file:
    name: mat-fhir-services.log
    clean-history-on-start: true
    max-history: 1

fhir:
  r4:
    baseurl: ${HAPI_FHIR_URL}
    public-url: ${HAPI_FHIR_URL_PUBLIC}

qdmqicore:
  conversion:
    baseurl: ${MAPPING_SERVICES_URL}

cql:
  conversion:
    baseurl: ${CQL_CONVERSION_URL}

self:
  health:
    baseurl: ${FHIR_SERVICES_URL}

json:
  data:
    url: ${CODESYSTEM_SHEET_URL}

mapping:
  services:
    baseUrl: ${MAPPING_SERVICES_URL}

swagger-server: ${MAT_FHIR_SWAGGER_URL}