spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mat?serverTimezone=UTC&max_allowed_packet=16777216
    username: mat
    password: mat
  jpa:
    hibernate.ddl-auto: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    show-sql: false
  data:
    mongodb:
      database: mat_conversion_results
      uri: mongodb://localhost

logging:
  level:
    root: INFO
    gov.cms.mat: DEBUG
    org.hl7.fhir.r4.hapi.ctx: WARN
    org.exolab: WARN
  file:
    name: mat-fhir-services.log

fhir:
  r4:
    baseurl: https://matdev.semanticbits.com/hapi-fhir-jpaserver/fhir

qdmqicore:
  conversion:
    baseurl: https://matdev.semanticbits.com/qdm-qicore-mapping-services/

cql:
  conversion:
    baseurl: https://matdev.semanticbits.com/cql-elm-translation/

self:
  health:
    baseurl: https://matdev.semanticbits.com/mat-fhir-serives/
