server:
  port: 9080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MAT_APP_BLANK?serverTimezone=UTC&max_allowed_packet=16777216
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    show-sql: false
  data:
    mongodb:
      database: mat_conversion_results
      uri: ${MONGO_DB_URL:mongodb://localhost:27018}

vsac-client:
  server: ${VSAC_VASE_URL:https://vsac.nlm.nih.gov}/vsac/ws/Ticket
  service: ${VSAC_VASE_URL}
  retrieve-multi-oids-service: ${VSAC_VASE_UR:https://vsac.nlm.nih.gov}/vsac/svs/RetrieveMultipleValueSets?
  profile-service: ${VSAC_VASE_URL:https://vsac.nlm.nih.gov}/vsac/profiles
  version-service: ${VSAC_VASE_URL:https://vsac.nlm.nih.gov}/vsac/oid/
  vsac-server-drc-url: ${VSAC_VASE_URL:https://vsac.nlm.nih.gov}/vsac
  use-cache: on
  cache-directory: /opt/vsac/cache

logging:
  level:
    root: WARN
    gov.cms.mat: DEBUG
    org.hl7.fhir.r4.hapi.ctx: INFO
    org.exolab: WARN
    org.springframework.data.mongodb.core.MongoTemplate: WARN
    org.hl7.fhir.r4.hapi.validation: WARN
  file:
    name: mat-fhir-services.log

fhir:
  r4:
    baseurl: ${HAPI_FHIR_URL:http://localhost:6060/hapi-fhir-jpaserver/fhir/}
    public-url: ${HAPI_FHIR_URL_PUBLIC:http://localhost:6060/hapi-fhir-jpaserver/fhir/}

qdmqicore:
  conversion:
    baseurl: ${QDM_QICORE_URL:http://localhost:9090}

cql:
  conversion:
    baseurl: ${CQL_CONVERSION_URL:http://localhost:7070}


self:
  health:
    baseurl: ${FHIR_SERVICES_URL:http://localhost:9080}

json:
  data:
    url: https://spreadsheets.google.com/feeds/list/15YvJbG3LsyqqN4ZIgRd88fgScbE95eK6fUilwHRw0Z0/od6/public/values?alt=json

swagger-server: