spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${MAT_DB_URL}
    username: ${MAT_DB_USER}
    password: ${MAT_DB_PASS}
  jpa:
    hibernate.ddl-auto: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    show-sql: false
  data:
    mongodb:
      database: mat_conversion_results
      uri: ${MONGO_DB_URL}

logging:
  level:
    root: INFO
    gov.cms.mat: DEBUG
    org.hl7.fhir.r4.hapi.ctx: WARN
    org.exolab: WARN
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  file:
    name: mat-fhir-services.log

fhir:
  r4:
    baseurl: ${HAPI_FHIR_URL}

qdmqicore:
  conversion:
    baseurl: ${QDM_QICORE_URL}

cql:
  conversion:
    baseurl: ${CQL_CONVERSION_URL}

self:
  health:
    baseurl: ${FHIR_SERVICES_URL}

