server:
  port: 9080

spring:
  profiles:
    active: local
  jpa:
    open-in-view: false

vsac-client:
  server: ${VSAC_VASE_URL}/vsac/ws/Ticket
  service: ${VSAC_SERVICE_URL}
  retrieve-multi-oids-service: ${VSAC_VASE_URL}/vsac/svs/RetrieveMultipleValueSets?
  profile-service: ${VSAC_VASE_URL}/vsac/profiles
  version-service: ${VSAC_VASE_URL}/vsac/oid/
  vsac-server-drc-url: ${VSAC_VASE_URL}/vsac
  use-cache: on
  cache-directory: /opt/vsac/cache

library-files:
  order:
    - FHIRHelpers_FHIR4-4.0.000.cql
    - SupplementalDataElements_FHIR4-1.0.000.cql
    - AdultOutpatientEncounters_FHIR4-1.1.000.cql
    - MATGlobalCommonFunctions_FHIR4-4.0.000.cql
    - AdvancedIllnessandFrailtyExclusion_FHIR4-4.0.000.cql
    - TJCOverall_FHIR4-4.0.000.cql
    - VTEICU_FHIR4-3.1.000.cql
    - Hospice_FHIR4-1.0.000.cql
    - NCQA_Common_FHIR4-5.1.000.cql

conversion-lib-lookup-4-1:
  map:
    FHIRHelpers: 4.0.001
    AdultOutpatientEncounters: 2.0.000
    AdvancedIllnessandFrailtyExclusion: 5.0.000
    Hospice: 2.0.000
    MATGlobalCommonFunctions: 5.0.000
    SupplementalDataElements: 2.0.000
    TJCOverall: 5.0.000
    VTEICU: 4.0.000

code-systemlookup-4-1:
  map:
    LOINC: http://loinc.org
    SNOMEDCT: http://snomed.info/sct/731000124108
    RoleCode: http://hl7.org/fhir/v3/RoleCode
    '2.16.840.1.113883.6.96': http://snomed.info/sct/731000124108

code-systemlookup-oid-4-1:
  map:
    LOINC: http://loinc.org
    '2.16.840.1.113883.6.96': http://snomed.info/sct/731000124108
    '2.16.840.1.113883.5.1001': http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    '2.16.840.1.113883.5.1': http://terminology.hl7.org/CodeSystem/v3-AdministrativeGender
    '2.16.840.1.113883.3.221.5': http://tobedone.com
    '2.16.840.1.113883.6.90': http://hl7.org/fhir/sid/icd-10-cm
    '2.16.840.1.113883.6.285': http://hl7.org/fhir/us/core/ValueSet-us-core-procedure-code.json.html
    '2.16.840.1.113883.12.112': http://tobedone.com
    '2.16.840.1.113883.6.1': http://loinc.org
    '2.16.840.1.113883.6.259': http://tobedone.com
    '2.16.840.1.113883.12.292': http://hl7.org/fhir/sid/cvx
    '2.16.840.1.113883.6.88': http://www.nlm.nih.gov/research/umls/rxnorm
    '2.16.840.1.113883.6.12':



    RoleCode: http://hl7.org/fhir/v3/RoleCode

measures:
  allowed:
    versions: v5.5,v5.6,v5.7,v5.8,v5.9,v6.0

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Mat Fhir Services


