server:
  port: 9080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mat_prd_dmp?serverTimezone=UTC&max_allowed_packet=16777216
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true

mat-api-key: ${MAT_API_KEY:LOCAL_KEY}

vsac-client:
  server: ${VSAC_VASE_URL:https://vsac.nlm.nih.gov}/vsac/ws/Ticket
  service: ${VSAC_VASE_URL:https://vsac.nlm.nih.gov}
  retrieve-multi-oids-service: ${VSAC_VASE_UR:https://vsac.nlm.nih.gov}/vsac/svs/RetrieveMultipleValueSets?
  profile-service: ${VSAC_VASE_URL:https://vsac.nlm.nih.gov}/vsac/profiles
  version-service: ${VSAC_VASE_URL:https://vsac.nlm.nih.gov}/vsac/oid/
  vsac-server-drc-url: ${VSAC_VASE_URL:https://vsac.nlm.nih.gov}/vsac
  use-cache: on
  cache-directory: /opt/vsac/cache

logging:
  level:
    root: WARN
    gov.cms.mat: DEBUG
    org.hl7.fhir.r4.hapi.ctx: INFO
    org.exolab: WARN
    org.springframework.data.mongodb.core.MongoTemplate: WARN
    org.hl7.fhir.r4.hapi.validation: WARN
    org.springframework.web.client.RestTemplate: WARN
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %mdc %-5level %logger{36}.%M - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %mdc %logger{36}.%M - %msg%n"
  file:
    name: mat-fhir-services.log


fhir:
  r4:
    baseurl: http://localhost:6060/fhir/
    public-url: http://localhost:6060/fhir/

mapping:
  services:
    baseUrl: ${MAPPING_SERVICES_URL:http://localhost:9090}

cql:
  conversion:
    baseurl: ${CQL_CONVERSION_URL:http://localhost:7070}

self:
  health:
    baseurl: ${FHIR_SERVICES_URL:http://localhost:9080}

json:
  data:
    url: https://spreadsheets.google.com/feeds/list/1_heoWR09X3UnyEvyyHLzVXT_D1Hhdt3OPztpgr1hW_k/od6/public/values?alt=json

swagger-server: