server:
  port: 9080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mat?serverTimezone=UTC&max_allowed_packet=16777216
    username: mat
    password: mat
  jpa:
    hibernate.ddl-auto: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true

mat-api-key: ${MAT_API_KEY:DISABLED}

fhir:
  r4:
    baseurl: http://localhost:6060/fhir/
    public-url: http://localhost:6060/fhir/

mapping:
  services:
    baseUrl: ${MAPPING_SERVICES_URL:http://localhost:9090}

cql:
  conversion:
    baseurl: ${CQL_CONVERSION_URL:http://localhost:7070}

self:
  health:
    baseurl: ${FHIR_SERVICES_URL:http://localhost:9080}

json:
  data:
    url: https://spreadsheets.google.com/feeds/list/1_heoWR09X3UnyEvyyHLzVXT_D1Hhdt3OPztpgr1hW_k/od6/public/values?alt=json

swagger-server:

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.exolab: WARN
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %mdc %-5level %logger{36}.%M - %msg%n"