version: '3.6'
services:
  hapi-fhir-jpaserver:
    image: hapi-fhir-jpaserver
    container_name: hapi-fhir-jpaserver
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HAPI_FHIR_URL_PUBLIC: ${HAPI_FHIR_URL_PUBLIC}
      HAPI_DB_URL: ${HAPI_DB_URL}
      HAPI_DB_USER: ${HAPI_DB_USER}
      HAPI_DB_PASS: ${HAPI_DB_PASS}
    ports:
      - 6060:6060