version: '3.6'
services:
  hapi-fhir-jpaserver_spring_boot:
    image: hapi-fhir-jpaserver_spring_boot
    container_name: hapi-fhir-jpaserver_spring_boot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HAPI_DB_URL: ${HAPI_DB_URL}
      HAPI_DB_USER: ${HAPI_DB_USER}
      HAPI_DB_PASS: ${HAPI_DB_PASS}
      HAPI_FHIR_URL_PUBLIC: ${HAPI_FHIR_URL_PUBLIC}
      MAT_API_KEY: ${MAT_API_KEY}
    ports:
      - 6060:6060