version: '3.6'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017


  mat-fhir-services:
    image: mat-fhir-services
    container_name: mat-fhir-services
    build:
      context: ../mat-fhir-services
      dockerfile: Dockerfile
    ports:
      - 9080:9080

  cql-elm-translation:
    image: cql-elm-translation
    container_name: cql-elm-translation
    build:
      context: ../cql-elm-translation/
      dockerfile: Dockerfile
    ports:
      - 7070:7070

  qdm-qicore-mapping-services:
    image: qdm-qicore-mapping-services
    container_name: qdm-qicore-mapping-services
    build:
      context: ../qdm-qicore-mapping-services
      dockerfile: Dockerfile
    ports:
      - 9090:9090
      