spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hapi-r4-db?serverTimezone=UTC&max_allowed_packet=16777216&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password

hapi:
  fhir:
    server:
      url: http://localhost:6060/fhir/

mat-api-key: ${MAT_API_KEY:LOCAL_KEY}