version: '3.6'

services:
  mapping-services:
    image: mapping-services
    container_name: mapping-services
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GOOGLE_QDM_QI_CORE_MAPPING_URL: ${GOOGLE_QDM_QI_CORE_MAPPING_URL}
      GOOGLE_DATA_TYPES_URL: ${GOOGLE_DATA_TYPES_URL}
      GOOGLE_REQJUIRED_MEASURE_FIELDS_URL: ${GOOGLE_REQJUIRED_MEASURE_FIELDS_URL}
      GOOGLE_RESOURCE_DEFINITION_URL: ${GOOGLE_RESOURCE_DEFINITION_URL}
    ports:
      - 7070:7070
