version: '3.6'

services:
  mapping-services:
    image: mapping-services
    container_name: mapping-services
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GOOGLE_MAT_ATTRIBUTES_URL: ${GOOGLE_MAT_ATTRIBUTES_URL}
      GOOGLE_QDM_QI_CORE_MAPPING_URL: ${GOOGLE_QDM_QI_CORE_MAPPING_URL}
      GOOGLE_DATA_TYPES_URL: ${GOOGLE_DATA_TYPES_URL}
      GOOGLE_REQUIRED_MEASURE_FIELDS_URL: ${GOOGLE_REQUIRED_MEASURE_FIELDS_URL}
      GOOGLE_RESOURCE_DEFINITION_URL: ${GOOGLE_RESOURCE_DEFINITION_URL}
      MAPPING_SWAGGER_URL: ${MAPPING_SWAGGER_URL}
      MAT_API_KEY: ${MAT_API_KEY}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - 9090:9090
