version: '3.6'

services:
  mat-fhir-services:
    image: mat-fhir-services
    container_name: mat-fhir-services
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VSAC_USER: ${VSAC_USER}
      VSAC_PASS: ${VSAC_PASS}
      MAT_DB: ${MAT_DB}
      MAT_DB_PASS: ${MAT_DB_PASS}
      MAT_DB_USER: ${MAT_DB_USER}
    ports:
      - 9080:9080