version: '3.6'

services:
  mat-fhir-services:
    image: mat-fhir-services
    container_name: mat-fhir-services
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VSAC_TICKET_URL_BASE: ${VSAC_TICKET_URL_BASE}
      VSAC_URL_BASE: ${VSAC_URL_BASE}
      MAT_DB_URL: ${MAT_DB_URL}
      MAT_DB_PASS: ${MAT_DB_PASS}
      MAT_DB_USER: ${MAT_DB_USER}
      HAPI_FHIR_URL: ${HAPI_FHIR_URL}
      CQL_CONVERSION_URL: ${CQL_CONVERSION_URL}
      FHIR_SERVICES_URL: ${FHIR_SERVICES_URL}
      MAT_LOG_LEVEL: ${MAT_LOG_LEVEL}
      CODESYSTEM_SHEET_URL: ${CODESYSTEM_SHEET_URL}
      HAPI_FHIR_URL_PUBLIC: ${HAPI_FHIR_URL_PUBLIC}
      MAT_FHIR_SWAGGER_URL: ${MAT_FHIR_SWAGGER_URL}
      MAPPING_SERVICES_URL: ${MAPPING_SERVICES_URL}
      MAT_API_KEY: ${MAT_API_KEY}
    ports:
      - 9080:9080