version: '3.6'

services:
  qdm-qicore-mapping-services:
    image: qdm-qicore-mapping-services
    container_name: qdm-qicore-mapping-services
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      QDM_SPREADSHEET: ${QDM_SPREADSHEET}
    ports:
      - 7070:7070

