server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"

json:
  data:
    url: https://spreadsheets.google.com/feeds/list/1uFtfWIHndogk-aoqROpuFSwHfcEKjaELw2Ph567uiNo/o7a94yh/public/values?alt=json






